version: "3.9"

services:
#  qdrant:
#    image: qdrant/qdrant:latest
#    container_name: qdrant
#    restart: unless-stopped
#    ports:
#      - "6333:6333"   # REST
#      - "6334:6334"   # gRPC
#    environment:
#      QDRANT_KEY: ${QDRANT_KEY}
#      QDRANT_URL: ${QDRANT_URL}
#    volumes:
#      - ./qdrant_data:/qdrant/storage
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
#      interval: 10s
#      timeout: 2s
#      retries: 30



  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # Bolt
    environment:
      NEO4J_AUTH: "${NEO4J_USERNAME}/${NEO4J_PASSWORD}"
      NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,gds.*"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"

    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
      - ./neo4j_import:/var/lib/neo4j/import
